import type { Achievement } from '@/types/minecraft'

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  // ================= STORY (16) =================
  {
    id: 'minecraft:story/root',
    title: 'Minecraft',
    description: 'The heart and story of the game',
    frame: 'TASK',
    icon: 'grass_block',
    category: 'story',
    categoryName: 'Story',
    parent: null,
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/mine_stone',
    title: 'Stone Age',
    description: 'Mine stone with your new pickaxe',
    frame: 'TASK',
    icon: 'wooden_pickaxe',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/upgrade_tools',
    title: 'Getting an Upgrade',
    description: 'Construct a better pickaxe',
    frame: 'TASK',
    icon: 'stone_pickaxe',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/mine_stone',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/smelt_iron',
    title: 'Acquire Hardware',
    description: 'Smelt an iron ingot',
    frame: 'TASK',
    icon: 'iron_ingot',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/upgrade_tools',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/obtain_armor',
    title: 'Suit Up',
    description: 'Protect yourself with a piece of iron armor',
    frame: 'TASK',
    icon: 'iron_chestplate',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/smelt_iron',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/lava_bucket',
    title: 'Hot Stuff',
    description: 'Fill a bucket with lava',
    frame: 'TASK',
    icon: 'lava_bucket',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/smelt_iron',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/iron_tools',
    title: "Isn't It Iron Pick",
    description: 'Upgrade your pickaxe',
    frame: 'TASK',
    icon: 'iron_pickaxe',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/smelt_iron',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/deflect_arrow',
    title: 'Not Today, Thank You',
    description: 'Deflect a projectile with a shield',
    frame: 'TASK',
    icon: 'shield',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/obtain_armor',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/form_obsidian',
    title: 'Ice Bucket Challenge',
    description: 'Obtain a block of obsidian',
    frame: 'TASK',
    icon: 'obsidian',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/lava_bucket',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/mine_diamond',
    title: 'Diamonds!',
    description: 'Acquire diamonds',
    frame: 'TASK',
    icon: 'diamond',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/iron_tools',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/enter_the_nether',
    title: 'We Need to Go Deeper',
    description: 'Build, light and enter a Nether Portal',
    frame: 'TASK',
    icon: 'flint_and_steel',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/form_obsidian',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/shiny_gear',
    title: 'Cover Me with Diamonds',
    description: 'Diamond armor saves lives',
    frame: 'TASK',
    icon: 'diamond_chestplate',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/mine_diamond',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/enchant_item',
    title: 'Enchanter',
    description: 'Enchant an item at an Enchanting Table',
    frame: 'TASK',
    icon: 'enchanting_table',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/mine_diamond',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/cure_zombie_villager',
    title: 'Zombie Doctor',
    description: 'Weaken and then cure a zombie villager',
    frame: 'GOAL',
    icon: 'golden_apple',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/smelt_iron',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:story/follow_ender_eye',
    title: 'Eye Spy',
    description: 'Follow an Ender Eye',
    frame: 'TASK',
    icon: 'ender_eye',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/enter_the_nether',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:story/enter_the_end',
    title: 'The End?',
    description: 'Enter the End Portal',
    frame: 'TASK',
    icon: 'end_stone',
    category: 'story',
    categoryName: 'Story',
    parent: 'minecraft:story/follow_ender_eye',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },

  // ================= NETHER (24) =================
  {
    id: 'minecraft:nether/root',
    title: 'Nether',
    description: 'Bring summer clothes',
    frame: 'TASK',
    icon: 'netherrack',
    category: 'nether',
    categoryName: 'Nether',
    parent: null,
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/return_to_sender',
    title: 'Return to Sender',
    description: 'Destroy a Ghast with a fireball',
    frame: 'CHALLENGE',
    icon: 'fire_charge',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/find_bastion',
    title: 'Those Were the Days',
    description: 'Enter a Bastion Remnant',
    frame: 'TASK',
    icon: 'polished_blackstone_bricks',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/obtain_ancient_debris',
    title: 'Hidden in the Depths',
    description: 'Obtain Ancient Debris',
    frame: 'TASK',
    icon: 'ancient_debris',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/fast_travel',
    title: 'Subspace Bubble',
    description: 'Use the Nether to travel 7 km in the Overworld',
    frame: 'CHALLENGE',
    icon: 'map',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/find_fortress',
    title: 'A Terrible Fortress',
    description: 'Break your way into a Nether Fortress',
    frame: 'TASK',
    icon: 'nether_bricks',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/obtain_crying_obsidian',
    title: 'Who is Cutting Onions?',
    description: 'Obtain Crying Obsidian',
    frame: 'TASK',
    icon: 'crying_obsidian',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/distract_piglin',
    title: 'Oh Shiny',
    description: 'Distract Piglins with Gold',
    frame: 'TASK',
    icon: 'gold_ingot',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/ride_strider',
    title: 'This Boat Has Legs',
    description: 'Ride a Strider with a Warped Fungus on a Stick',
    frame: 'TASK',
    icon: 'warped_fungus_on_a_stick',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/uneasy_alliance',
    title: 'Uneasy Alliance',
    description: 'Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it',
    frame: 'CHALLENGE',
    icon: 'ghast_tear',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/loot_bastion',
    title: 'War Pigs',
    description: 'Loot a chest in a Bastion Remnant',
    frame: 'TASK',
    icon: 'chest',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/find_bastion',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/use_lodestone',
    title: 'Country Lode, Take Me Home',
    description: 'Use a Compass on a Lodestone',
    frame: 'TASK',
    icon: 'lodestone',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/netherite_armor',
    title: 'Cover Me in Debris',
    description: 'Get a full suit of Netherite armor',
    frame: 'CHALLENGE',
    icon: 'netherite_chestplate',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/obtain_ancient_debris',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/get_wither_skull',
    title: 'Spooky Scary Skeleton',
    description: "Obtain a Wither Skeleton's skull",
    frame: 'TASK',
    icon: 'wither_skeleton_skull',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/find_fortress',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/obtain_blaze_rod',
    title: 'Into Fire',
    description: 'Relieve a Blaze of its rod',
    frame: 'TASK',
    icon: 'blaze_rod',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/find_fortress',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/charge_respawn_anchor',
    title: 'Not Quite "Nine" Lives',
    description: 'Charge a Respawn Anchor to the maximum',
    frame: 'TASK',
    icon: 'respawn_anchor',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/obtain_crying_obsidian',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/ride_strider_in_overworld_lava',
    title: 'Feels Like Home',
    description: 'Take a Strider for a loooong ride on a lava lake in the Overworld',
    frame: 'TASK',
    icon: 'warped_fungus_on_a_stick',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/ride_strider',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/explore_nether',
    title: 'Hot Tourist Destinations',
    description: 'Explore all Nether biomes',
    frame: 'CHALLENGE',
    icon: 'netherite_boots',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/root',
    criteriaCount: 5,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/summon_wither',
    title: 'Withering Heights',
    description: 'Summon the Wither',
    frame: 'TASK',
    icon: 'nether_star',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/get_wither_skull',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/brew_potion',
    title: 'Local Brewery',
    description: 'Brew a potion',
    frame: 'TASK',
    icon: 'potion',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/obtain_blaze_rod',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:nether/create_beacon',
    title: 'Bring Home the Beacon',
    description: 'Construct and place a Beacon',
    frame: 'TASK',
    icon: 'beacon',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/summon_wither',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/all_potions',
    title: 'A Furious Cocktail',
    description: 'Have every potion effect applied at the same time',
    frame: 'CHALLENGE',
    icon: 'milk_bucket',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/brew_potion',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/create_full_beacon',
    title: 'Beaconator',
    description: 'Bring a beacon to full power',
    frame: 'GOAL',
    icon: 'beacon',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/create_beacon',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:nether/all_effects',
    title: 'How Did We Get Here?',
    description: 'Have every effect applied at the same time',
    frame: 'CHALLENGE',
    icon: 'bucket',
    category: 'nether',
    categoryName: 'Nether',
    parent: 'minecraft:nether/all_potions',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },

  // ================= THE END (9) =================
  {
    id: 'minecraft:end/root',
    title: 'The End',
    description: 'Or the beginning?',
    frame: 'TASK',
    icon: 'end_stone',
    category: 'end',
    categoryName: 'The End',
    parent: null,
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:end/kill_dragon',
    title: 'Free the End',
    description: 'Good luck',
    frame: 'TASK',
    icon: 'dragon_head',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:end/dragon_egg',
    title: 'The Next Generation',
    description: 'Hold the Dragon Egg',
    frame: 'GOAL',
    icon: 'dragon_egg',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/kill_dragon',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:end/enter_end_gateway',
    title: 'Remote Getaway',
    description: 'Escape the island',
    frame: 'TASK',
    icon: 'ender_pearl',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/kill_dragon',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:end/respawn_dragon',
    title: 'The End... Again...',
    description: 'Respawn the Ender Dragon',
    frame: 'GOAL',
    icon: 'end_crystal',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/kill_dragon',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:end/dragon_breath',
    title: 'You Need a Mint',
    description: "Collect Dragon's Breath in a Glass Bottle",
    frame: 'GOAL',
    icon: 'dragon_breath',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/kill_dragon',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:end/find_end_city',
    title: 'The City at the End of the Game',
    description: 'Go on in, what could happen?',
    frame: 'TASK',
    icon: 'purpur_block',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/enter_end_gateway',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:end/elytra',
    title: "Sky's the Limit",
    description: 'Find Elytra',
    frame: 'GOAL',
    icon: 'elytra',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/find_end_city',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:end/levitate',
    title: 'Great View From Up Here',
    description: 'Levitate up 50 blocks from the attacks of a Shulker',
    frame: 'CHALLENGE',
    icon: 'shulker_shell',
    category: 'end',
    categoryName: 'The End',
    parent: 'minecraft:end/find_end_city',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },

  // ================= ADVENTURE (47) =================
  {
    id: 'minecraft:adventure/root',
    title: 'Adventure',
    description: 'Adventure, exploration and combat',
    frame: 'TASK',
    icon: 'map',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: null,
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/voluntary_exile',
    title: 'Voluntary Exile',
    description: 'Kill a raid captain',
    frame: 'TASK',
    icon: 'ominous_banner',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/kill_a_mob',
    title: 'Monster Hunter',
    description: 'Kill any hostile monster',
    frame: 'TASK',
    icon: 'iron_sword',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/trade',
    title: 'What a Deal!',
    description: 'Successfully trade with a Villager',
    frame: 'TASK',
    icon: 'emerald',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/sleep_in_bed',
    title: 'Sweet Dreams',
    description: 'Sleep in a bed to change your respawn point',
    frame: 'TASK',
    icon: 'red_bed',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/shoot_arrow',
    title: 'Take Aim',
    description: 'Shoot something with an arrow',
    frame: 'TASK',
    icon: 'bow',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/kill_a_mob',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/throw_trident',
    title: 'A Throwaway Joke',
    description: 'Throw a Trident at something',
    frame: 'TASK',
    icon: 'trident',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/summon_iron_golem',
    title: 'Hired Help',
    description: 'Summon an Iron Golem to help defend a village',
    frame: 'GOAL',
    icon: 'iron_block',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/ol_betsy',
    title: "Ol' Betsy",
    description: 'Shoot a Crossbow',
    frame: 'TASK',
    icon: 'crossbow',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/kill_a_mob',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/hero_of_the_village',
    title: 'Hero of the Village',
    description: 'Successfully defend a village from a raid',
    frame: 'CHALLENGE',
    icon: 'emerald',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/voluntary_exile',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/two_birds_one_arrow',
    title: 'Two Birds, One Arrow',
    description: 'Kill two Phantoms with a piercing arrow',
    frame: 'CHALLENGE',
    icon: 'crossbow',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/ol_betsy',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/whos_the_pillager_now',
    title: "Who's the Pillager Now?",
    description: 'Give a Pillager a taste of their own medicine',
    frame: 'TASK',
    icon: 'crossbow',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/ol_betsy',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/arbalistic',
    title: 'Arbalistic',
    description: 'Kill five unique mobs with one crossbow shot',
    frame: 'CHALLENGE',
    icon: 'crossbow',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/ol_betsy',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/adventuring_time',
    title: 'Adventuring Time',
    description: 'Discover every biome',
    frame: 'CHALLENGE',
    icon: 'diamond_boots',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 52,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/very_very_frightening',
    title: 'Very Very Frightening',
    description: 'Strike a Villager with lightning',
    frame: 'CHALLENGE',
    icon: 'trident',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/throw_trident',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/sniper_duel',
    title: 'Sniper Duel',
    description: 'Kill a Skeleton with an arrow from more than 50 meters away',
    frame: 'CHALLENGE',
    icon: 'arrow',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/shoot_arrow',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/bullseye',
    title: 'Bullseye',
    description: 'Hit the bullseye of a Target block from at least 30 meters away',
    frame: 'CHALLENGE',
    icon: 'target',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/shoot_arrow',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/kill_all_mobs',
    title: 'Monsters Hunted',
    description: 'Kill one of every hostile monster',
    frame: 'CHALLENGE',
    icon: 'diamond_sword',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/kill_a_mob',
    criteriaCount: 34,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/totem_of_undying',
    title: 'Postmortal',
    description: 'Use a Totem of Undying to cheat death',
    frame: 'GOAL',
    icon: 'totem_of_undying',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/kill_a_mob',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/play_jukebox_in_meadows',
    title: 'Sound of Music',
    description: 'Make the Meadows come alive with the sound of music from a Jukebox',
    frame: 'TASK',
    icon: 'jukebox',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/walk_on_powder_snow_with_leather_boots',
    title: 'Light as a Rabbit',
    description: 'Walk on powder snow... without sinking into it',
    frame: 'TASK',
    icon: 'leather_boots',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/spyglass_at_parrot',
    title: 'Is It a Bird?',
    description: 'Look at a Parrot through a Spyglass',
    frame: 'TASK',
    icon: 'spyglass',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/spyglass_at_ghast',
    title: 'Is It a Balloon?',
    description: 'Look at a Ghast through a Spyglass',
    frame: 'TASK',
    icon: 'spyglass',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/spyglass_at_parrot',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/spyglass_at_dragon',
    title: 'Is It a Plane?',
    description: 'Look at the Ender Dragon through a Spyglass',
    frame: 'TASK',
    icon: 'spyglass',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/spyglass_at_ghast',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/fall_from_world_height',
    title: 'Caves & Cliffs',
    description: 'Free fall from the top of the world to the bottom',
    frame: 'TASK',
    icon: 'water_bucket',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/avoid_vibration',
    title: 'Sneak 100',
    description: 'Sneak near a Sculk Sensor or Warden to prevent it detecting you',
    frame: 'TASK',
    icon: 'sculk_sensor',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/kill_mob_near_sculk_catalyst',
    title: 'It Spreads',
    description: 'Kill a mob near a Sculk Catalyst',
    frame: 'TASK',
    icon: 'sculk_catalyst',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/avoid_vibration',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/trim_with_any_armor_pattern',
    title: 'Crafting a New Look',
    description: 'Craft a trimmed armor at a Smithing Table',
    frame: 'TASK',
    icon: 'smithing_table',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/trim_with_all_exclusive_armor_patterns',
    title: 'Smithing with Style',
    description: 'Apply these smithing templates at least once',
    frame: 'CHALLENGE',
    icon: 'smithing_table',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/trim_with_any_armor_pattern',
    criteriaCount: 8,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/salvage_sherd',
    title: 'Respecting the Remnants',
    description: 'Brush a Suspicious block to obtain a Pottery Sherd',
    frame: 'TASK',
    icon: 'brush',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/craft_decorated_pot_using_only_sherds',
    title: 'Careful Restoration',
    description: 'Make a Decorated Pot out of 4 Pottery Sherds',
    frame: 'TASK',
    icon: 'decorated_pot',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/salvage_sherd',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/read_power_of_chiseled_bookshelf',
    title: 'The Power of Books',
    description: 'Read the power signal of a Chiseled Bookshelf using a Comparator',
    frame: 'TASK',
    icon: 'chiseled_bookshelf',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/brush_armadillo',
    title: "Isn't It Scute?",
    description: 'Brush an Armadillo to obtain an Armadillo Scute',
    frame: 'TASK',
    icon: 'armadillo_scute',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/salvage_sherd',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/who_needs_rockets',
    title: 'Who Needs Rockets?',
    description: 'Launch yourself up at least 7 blocks using a Wind Charge',
    frame: 'TASK',
    icon: 'wind_charge',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/crafters_crafting_crafters',
    title: 'Crafters Crafting Crafters',
    description: 'Be near a Crafter when it crafts a Crafter',
    frame: 'CHALLENGE',
    icon: 'crafter',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/lighten_up',
    title: 'Lighten Up',
    description: 'Un-oxidize a Copper Bulb using an Axe',
    frame: 'TASK',
    icon: 'copper_bulb',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/under_lock_and_key',
    title: 'Under Lock and Key',
    description: 'Unlock a Trial Spawner or Vault using a Trial Key',
    frame: 'TASK',
    icon: 'trial_key',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/revaulting',
    title: 'Revaulting',
    description: 'Unlock an Ominous Vault using an Ominous Trial Key',
    frame: 'GOAL',
    icon: 'ominous_trial_key',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/under_lock_and_key',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/blowback',
    title: 'Blowback',
    description: 'Defeat a Breeze with a deflected Wind Charge',
    frame: 'CHALLENGE',
    icon: 'wind_charge',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/who_needs_rockets',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/over_overkill',
    title: 'Over-Overkill',
    description: 'Deal 50 hearts of damage in a single hit using a Mace',
    frame: 'CHALLENGE',
    icon: 'mace',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/trade_at_world_height',
    title: 'Star Trader',
    description: 'Trade with a Villager at the build height limit',
    frame: 'GOAL',
    icon: 'emerald',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/trade',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/honey_block_slide',
    title: 'Sticky Situation',
    description: 'Jump into a Honey Block to break your fall',
    frame: 'TASK',
    icon: 'honey_block',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/lightning_rod_with_villager_no_fire',
    title: 'Surge Protector',
    description: 'Protect a Villager from an undesired shock without starting a fire',
    frame: 'TASK',
    icon: 'lightning_rod',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/walk_on_lava_with_boots',
    title: 'Walk the Walk',
    description: 'Walk safely over lava with Netherite boots',
    frame: 'TASK',
    icon: 'netherite_boots',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/fall_with_mace',
    title: 'Mace to Face',
    description: 'Hit a target while falling using a Mace',
    frame: 'TASK',
    icon: 'mace',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/over_overkill',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:adventure/use_vault',
    title: 'Unlock the Vault',
    description: 'Unlock a Vault with a Trial Key',
    frame: 'TASK',
    icon: 'vault',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/under_lock_and_key',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:adventure/ominous_trial_spawner',
    title: 'A Real Challenge',
    description: 'Trigger an Ominous Trial Spawner',
    frame: 'TASK',
    icon: 'trial_spawner',
    category: 'adventure',
    categoryName: 'Adventure',
    parent: 'minecraft:adventure/under_lock_and_key',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },

  // ================= HUSBANDRY (37) =================
  {
    id: 'minecraft:husbandry/root',
    title: 'Husbandry',
    description: 'The world is full of friends and food',
    frame: 'TASK',
    icon: 'wheat',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: null,
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/breed_an_animal',
    title: 'The Parrots and the Bats',
    description: 'Breed two animals together',
    frame: 'TASK',
    icon: 'wheat',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/tame_an_animal',
    title: 'Best Friends Forever',
    description: 'Tame an animal',
    frame: 'TASK',
    icon: 'lead',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/plant_seed',
    title: 'A Seedy Place',
    description: 'Plant a seed and watch it grow',
    frame: 'TASK',
    icon: 'wheat_seeds',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/bred_all_animals',
    title: 'Two by Two',
    description: 'Breed all the animals!',
    frame: 'CHALLENGE',
    icon: 'golden_carrot',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/breed_an_animal',
    criteriaCount: 23,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/balanced_diet',
    title: 'A Balanced Diet',
    description: 'Eat everything that is edible, even if it is not good for you',
    frame: 'CHALLENGE',
    icon: 'apple',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/plant_seed',
    criteriaCount: 40,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/break_diamond_hoe',
    title: 'Serious Dedication',
    description: 'Completely use up a diamond hoe, and then reevaluate your life choices',
    frame: 'CHALLENGE',
    icon: 'diamond_hoe',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/tactical_fishing',
    title: 'Tactical Fishing',
    description: 'Catch a fish... without a fishing rod!',
    frame: 'TASK',
    icon: 'water_bucket',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/silk_touch_nest',
    title: 'Total Beelocation',
    description: 'Move a Bee Nest with 3 Bees inside using Silk Touch',
    frame: 'GOAL',
    icon: 'bee_nest',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/safely_harvest_honey',
    title: 'Bee Our Guest',
    description: 'Use a Campfire to collect Honey without aggravating the bees',
    frame: 'TASK',
    icon: 'honey_bottle',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/wax_on',
    title: 'Wax On',
    description: 'Apply Honeycomb to a Copper block!',
    frame: 'TASK',
    icon: 'honeycomb',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/safely_harvest_honey',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/wax_off',
    title: 'Wax Off',
    description: 'Scrape wax off a Copper block!',
    frame: 'TASK',
    icon: 'stone_axe',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/wax_on',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/axolotl_in_a_bucket',
    title: 'The Cutest Predator',
    description: 'Catch an Axolotl in a bucket',
    frame: 'TASK',
    icon: 'axolotl_bucket',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/tactical_fishing',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/kill_axolotl_target',
    title: 'The Healing Power of Friendship!',
    description: 'Team up with an Axolotl and win a fight',
    frame: 'TASK',
    icon: 'tropical_fish_bucket',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/axolotl_in_a_bucket',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/froglights',
    title: 'With Our Powers Combined!',
    description: 'Have all Froglights in your inventory',
    frame: 'CHALLENGE',
    icon: 'ochre_froglight',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 3,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/leash_all_frog_variants',
    title: 'When the Squad Hops into Town',
    description: 'Get each Frog variant on a Lead',
    frame: 'TASK',
    icon: 'lead',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 3,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/tadpole_in_a_bucket',
    title: 'Bukkit Bukkit',
    description: 'Catch a Tadpole in a Bucket',
    frame: 'TASK',
    icon: 'tadpole_bucket',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/tactical_fishing',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/allay_drop_item_to_dump',
    title: "You've Got a Friend in Me",
    description: 'Have an Allay deliver items to you',
    frame: 'TASK',
    icon: 'cookie',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/allay_deliver_cake_to_note_block',
    title: 'Birthday Song',
    description: 'Have an Allay drop a Cake at a Note Block',
    frame: 'CHALLENGE',
    icon: 'cake',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/allay_drop_item_to_dump',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/sniff_sniffer',
    title: 'Smells Interesting',
    description: 'Obtain a Sniffer Egg',
    frame: 'TASK',
    icon: 'sniffer_egg',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/feed_snifflet',
    title: 'Little Sniffs',
    description: 'Feed a Snifflet',
    frame: 'TASK',
    icon: 'torchflower_seeds',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/sniff_sniffer',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/obtain_sniffer_egg',
    title: 'Planting the Past',
    description: 'Plant any Sniffer seed',
    frame: 'TASK',
    icon: 'pitcher_pod',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/feed_snifflet',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/complete_catalogue',
    title: 'A Complete Catalogue',
    description: 'Tame all cat variants!',
    frame: 'CHALLENGE',
    icon: 'cod',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/tame_an_animal',
    criteriaCount: 11,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/fishy_business',
    title: 'Fishy Business',
    description: 'Catch a fish using a fishing rod',
    frame: 'TASK',
    icon: 'fishing_rod',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/ride_a_boat_with_a_goat',
    title: 'Whatever Floats Your Goat!',
    description: 'Get in a Boat and float with a Goat',
    frame: 'TASK',
    icon: 'oak_boat',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/make_a_sign_glow',
    title: 'Glow and Behold!',
    description: 'Make the text of a Sign glow with a Glow Ink Sac',
    frame: 'TASK',
    icon: 'glow_ink_sac',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/obtain_netherite_hoe',
    title: 'Serious Dedication',
    description: 'Upgrade a Hoe to Netherite',
    frame: 'CHALLENGE',
    icon: 'netherite_hoe',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/break_diamond_hoe',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/repair_wolf_armor',
    title: 'Good as New',
    description: 'Repair damaged Wolf Armor using Armadillo Scutes',
    frame: 'TASK',
    icon: 'wolf_armor',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/tame_an_animal',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/remove_wolf_armor',
    title: 'Shear Brilliance',
    description: 'Remove Wolf Armor from a Wolf using Shears',
    frame: 'TASK',
    icon: 'shears',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/repair_wolf_armor',
    criteriaCount: 1,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/whole_pack',
    title: 'The Whole Pack',
    description: 'Tame one of each Wolf variant',
    frame: 'CHALLENGE',
    icon: 'bone',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/tame_an_animal',
    criteriaCount: 9,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/allay_deliver_item_to_player',
    title: 'Delivery Service',
    description: 'Have an Allay deliver items to a player',
    frame: 'TASK',
    icon: 'cookie',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/allay_drop_item_to_dump',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/leash_all_horse_variants',
    title: 'The Whole Herd',
    description: 'Leash each horse variant',
    frame: 'TASK',
    icon: 'lead',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/tame_an_animal',
    criteriaCount: 5,
    completedCount: 0,
    completedPercentage: 0,
  },
  {
    id: 'minecraft:husbandry/brush_armadillo',
    title: "Isn't It Scute?",
    description: 'Brush an Armadillo to get Armadillo Scutes',
    frame: 'TASK',
    icon: 'armadillo_scute',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/root',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/feed_armadillo',
    title: 'Armadillo Armor',
    description: 'Feed an Armadillo with Spider Eyes',
    frame: 'TASK',
    icon: 'spider_eye',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/brush_armadillo',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/obtain_wolf_armor',
    title: 'Suit Up Your Pup',
    description: 'Equip Wolf Armor onto a tamed Wolf',
    frame: 'TASK',
    icon: 'wolf_armor',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/brush_armadillo',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/place_hanging_sign',
    title: 'Hang in There',
    description: 'Place a Hanging Sign',
    frame: 'TASK',
    icon: 'oak_hanging_sign',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/make_a_sign_glow',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
  {
    id: 'minecraft:husbandry/feed_allay',
    title: 'Sweet Treat',
    description: 'Give an Allay something sweet',
    frame: 'TASK',
    icon: 'sugar',
    category: 'husbandry',
    categoryName: 'Husbandry',
    parent: 'minecraft:husbandry/allay_drop_item_to_dump',
    criteriaCount: 1,
    completedCount: 1,
    completedPercentage: 100,
  },
]

export const DEFAULT_CATEGORIES = [
  'story',
  'nether',
  'end',
  'adventure',
  'husbandry',
]
