services:
  cdn:
    container_name: cdn
    build: .
    restart: unless-stopped
    image: smonolo/cdn
    ports:
      - '49160:49160'
    volumes:
      - '${CDN_IMAGES_PATH}:/images'
      - '${CDN_CONFIG_PATH}:/config'
