services:
  cdn:
    image: smonolo/cdn
    container_name: cdn
    restart: unless-stopped
    build: .
    ports:
      - '49160:49160'
    volumes:
      - '${CDN_IMAGES_PATH}:/images'
      - '${CDN_CONFIG_PATH}:/config'
    network:
      - caddy_network

networks:
  caddy_network:
    name: caddy_network
