services:
  cdn:
    image: ghcr.io/smonolo/cdn:latest
    container_name: cdn
    restart: unless-stopped
    ports:
      - '49160:49160'
    volumes:
      - '${CDN_IMAGES_PATH}:/images'
      - '${CDN_FILES_PATH}:/files'
      - '${CDN_CONFIG_PATH}:/config'
    networks:
      - caddy_network

networks:
  caddy_network:
    name: caddy_network
    external: true
