name: Build and push CDN

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - apps/cdn/**

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: ./apps/cdn
          file: ./apps/cdn/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cdn:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cdn:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cdn:cache,mode=max

      - uses: actions/delete-package-versions@v5
        with:
          package-name: cdn
          package-type: container
          min-versions-to-keep: 1
          token: ${{ secrets.GITHUB_TOKEN }}
