name: Build and push CDN

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - apps/cdn/**

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - uses: docker/build-push-action@v6
        with:
          context: ./apps/cdn
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/cdn:latest
